### ISSUE TITLE
locals always want to buy

### ISSUE THREAD

**Issue by GlobbinTerpenes** [itsxScrubz/scrubz_drugs#2]
even if a player has no drugs on them the loclas show the prompt

**Comment by itsxScrubz** [comment]
Its because I'm not checking for drugs before drawing the text. You can change that by just using a callback before drawing the text. But I'll leave that up to the people using the script to change.

**Comment by GlobbinTerpenes** [comment]
how would i do that? the script breaks when someone tries to sell without any

**Comment by itsxScrubz** [comment]
It might be due to how I have the threads set up. Just insert the callback in the thread responsible for drawing text, and add the callback before it draws text, and only draw it if the player has drugs. If that doesn't work you might have to restructure the threads.
