### ISSUE TITLE
Issue while cooking

### ISSUE THREAD

**Issue by KacpereQ02** [itsxScrubz/scrubz_drugs#3]
InvokeNative: execution failed: Argument at index 1 was null.
SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed.

Everytime i try to cook drugs, it shuts off the script and doesn't have any options to even leave the building.

**Comment by itsxScrubz** [comment]
I actually didn't notice this issue until now. I don't have any issues with the script, nor has anyone else reported this issue.... which would cause me to assume this is being caused by something outside of my code.
