### ISSUE TITLE
coords

### ISSUE THREAD

**Issue by ZockerBoysHD** [itsxScrubz/scrubz_drugs#5]
so i have figuered out some stuff on my own but im stil lkinda confused how this sscript works

so u need a recipe and ressources (which u get from raids)
to cook the drugs, right?

1. where are those recepies locatet 
2. where are the material raid things located
3. what does this deadly force thing mean?

**Comment by itsxScrubz** [comment]
1) There is a pic in the readme where the default locations are. The needed materials and amounts are located inside sv_locations.lua
2) The raid is located at the morgue near the forum drive/grove st area. If you don't know where that is google it. 
3) It's just a warning that being in the area means your shoot on site. You can remove that if you want.
