### ISSUE TITLE
Dispatch

### ISSUE THREAD

**Issue by ZockerBoysHD** [itsxScrubz/scrubz_drugs#6]
where can if find ur visualdispatch system?? i cna enable it in the config but cant find it online

**Comment by itsxScrubz** [comment]
You can't. It's not a public resource.

**Comment by ZockerBoysHD** [comment]
then why is it inside the drug ressource lol?

**Comment by itsxScrubz** [comment]
Because before my own framework, I was using esx along with this drugs script. I added the a few thing but forgot to remove the code associated with the visual dispatch. I no longer use this resource nor maintain it, so I've just never removed it.
